**Ikhlaq Ahmad**

**NetID: ixa190000**

**Assignment: Text Classification**

**CS 4395 - Dr. Mazidi**

### **Text Classification**

The purpose of this notebook is to utilize sklearn libraray to classify a data set using different probablistic approaches. For this notebook, the following techniques were used:

1. Naive Bayes
2. Logistic Regression
3. Neural Networks  

Data set: amazon_books_Data.csv

All three techniques use multiclass appraoch and the same data to find out the accuracy impact.




In [882]:
# imports
import pandas as pd
import numpy as np

# csv file only gets columns 14 - 16
file_data = pd.read_csv("/content/amazon_books_Data.csv", header=0, usecols=[14, 16])
print('rows and columns:', file_data.shape)
print(file_data.head())

rows and columns: (100, 2)
                                         review_body Sentiment_books
0               "I love it and so does my students!"        positive
1  "My wife and I ordered 2 books and gave them a...        positive
2  "Great book just like all the others in the se...        positive
3                                     "So beautiful"        positive
4  "Enjoyed the author's story and his quilts are...        positive


In [883]:
# set up X and y
X = file_data.review_body
y = file_data.Sentiment_books

# X
X.head()

0                 "I love it and so does my students!"
1    "My wife and I ordered 2 books and gave them a...
2    "Great book just like all the others in the se...
3                                       "So beautiful"
4    "Enjoyed the author's story and his quilts are...
Name: review_body, dtype: object

In [884]:
# y
y[:16]

0     positive
1     positive
2     positive
3     positive
4     positive
5     negaitve
6     positive
7     positive
8     positive
9     positive
10    positive
11    positive
12    positive
13    positive
14    negaitve
15    positive
Name: Sentiment_books, dtype: object

In [885]:
# train text
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=1234)

X_train.shape

(80,)

In [886]:
# remove stop words using nltk
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# initializer tf-idf vectorizor
from sklearn.feature_extraction.text import TfidfVectorizer

stopwords = stopwords.words('english')
vectorizer = TfidfVectorizer(stop_words = stopwords)
vectorizer.fit(X_train)

# apply tfidf vectorizer
X_train = vectorizer.fit_transform(X_train)  # fit and transform the train data
X_test = vectorizer.transform(X_test)        # transform only the test data


In [887]:
# print vocabualry and its length
print("Vocabulary: ", vectorizer.vocabulary_)
print("Lenght: ", len(vectorizer.vocabulary_))

Vocabulary:  {'quality': 761, 'product': 744, 'fast': 348, 'shipping': 862, 'great': 420, 'like': 563, 'fact': 340, 'small': 879, 'easy': 283, 'save': 828, 'store': 915, 'wedding': 1060, 'day': 229, 'wait': 1045, 'use': 1031, 'helpful': 448, 'med': 603, 'surg': 941, 'class': 175, 'used': 1032, 'study': 926, 'exams': 326, 'addition': 22, 'test': 971, 'books': 123, 'really': 776, 'summarized': 932, 'system': 951, 'focused': 371, 'nclex': 640, 'thought': 984, 'important': 476, 'still': 913, 'working': 1076, 'john': 512, 'fitzgerald': 366, 'interest': 497, 'full': 390, 'disclosure': 266, 'worked': 1075, 'together': 994, 'red': 783, 'hen': 452, 'press': 739, 'would': 1081, 'nudge': 659, 'say': 830, 'book': 122, 'mind': 610, '34': 7, 'skynet': 876, 'becomes': 100, 'self': 846, 'aware': 85, '14': 1, 'eastern': 282, 'time': 991, 'august': 76, '29th': 6, 'sense': 847, 'long': 575, 'solipsistic': 884, 'narcissistic': 637, 'way': 1056, 'keen': 516, 'observer': 664, 'consumer': 197, 'origins': 681

In [888]:
# sparse matrix

print('train size:', X_train.shape)
print(X_train.toarray()[:5])

print('\ntest size:', X_test.shape)
print(X_test.toarray()[:5])

train size: (80, 1095)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.05641973 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

test size: (20, 1095)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [910]:
#X and Y training using mulitnomial NB
from sklearn.naive_bayes import MultinomialNB

naive_bayes = MultinomialNB()
naive_bayes.fit(X_train, y_train)

MultinomialNB()

In [912]:
# Log NB
naive_bayes.class_log_prior_[1]

-0.14792013007662153

In [913]:
# Log pob using NB
naive_bayes.feature_log_prob_

array([[-6.96885799, -6.92137959, -6.91163916, ..., -6.96885799,
        -7.05021421, -6.65774295],
       [-7.18281505, -7.12792947, -7.18281505, ..., -7.18281505,
        -6.99315153, -7.18281505]])

In [914]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# make predictions on the test data
pred = naive_bayes.predict(X_test)

# print confusion matrix
print(confusion_matrix(y_test, pred))

[[ 0  5]
 [ 0 15]]



accuracy score:  0.75

precision score (positive):  0.75

recall score: (positive):  1.0

f1 score:  0.8571428571428571


In [920]:
# Stats
print('positive(s) in test data:',y_test[y_test=="positive"].shape[0])
print('negative(s) in test data:',y_test[y_test=="negaitve"].shape[0])
print('test size: ', len(y_test))

baseline = y_test[y_test=="positive"].shape[0] / y_test.shape[0] 
print("Positive %: ", baseline)

baseline = y_test[y_test=="negaitve"].shape[0] / y_test.shape[0] 
print("Negative %: ", baseline)


print('accuracy score: ', accuracy_score(y_test, pred))
print('precision score (positive): ', precision_score(y_test, pred, pos_label="positive"))
print('recall score: (positive): ', recall_score(y_test, pred, pos_label="positive"))
      
print("f1 score: ", f1_score(y_test, pred, pos_label="positive"))

positive(s) in test data: 15
negative(s) in test data: 5
test size:  20
Positive %:  0.75
Negative %:  0.25
accuracy score:  0.75
precision score (positive):  0.75
recall score: (positive):  1.0
f1 score:  0.8571428571428571


In [921]:
# Missed
y_test[y_test != pred]

42    negaitve
33    negaitve
59    negaitve
94    negaitve
96    negaitve
Name: Sentiment_books, dtype: object

## Logic Regression

In [929]:
# imports
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix, accuracy_score 

In [899]:
# Making the logistic regression model
logistic_model = LogisticRegression()

In [923]:
# Training the model on the training data and labels using the same data
logistic_model.fit(X_train, y_train)

LogisticRegression()

In [924]:
# Using the model to predict the labels of the test data
y_pred = logistic_model.predict(X_test)

In [927]:
# Evaluating the accuracy of the model using the sklearn functions
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

In [926]:
# Printing the results
print("Accuracy: ",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy is 75.0
Confusion Matrix
[[ 0  5]
 [ 0 15]]


## Neural Networks

In [928]:
# imports
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [930]:
# Neural Network Classifier
NN = MLPClassifier()

In [932]:
# Training the model on the training data and labels using the same data
NN.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [933]:
# predicting the labels of the test data.
y_pred = NN.predict(X_test)

In [908]:
# Step 5
# Evaluating the results of the model
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

In [909]:
# Step 6
# Printing the Results
print("Accuracy for Neural Network is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy for Neural Network is: 75.0
Confusion Matrix
[[ 0  5]
 [ 0 15]]
